[package]
name = "usls"
version = "0.0.2"
edition = "2021"
description = "A Rust library integrated with ONNXRuntime, providing a collection of ML models."
repository = "https://github.com/jamjamjon/usls"
authors = ["Jamjamjon <jamjamjon.usls@gmail.com>"]
license = "MIT"
readme = "README.md"
exclude = ["assets/*", "examples/*"]

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
image = { version = "0.24.7", default-features = false, features = [
    "jpeg", 
    "png", 
    "tiff", 
    "webp", 
    "webp-encoder",
    "bmp"
]}
imageproc = { version = "0.23.0", default-features = false }
ndarray = { version = "0.15.6" }
# ort-sys = { version = "2.0.0-alpha.4" }
# ort = { version = "2.0.0-alpha.4", default-features = false, features = ["load-dynamic", "copy-dylibs", "half", "ndarray", "cuda", "tensorrt", "coreml", "openvino"] }
ort = { version = "2.0.0-alpha.4", default-features = false, features = ["load-dynamic", "copy-dylibs", "profiling", "half", "ndarray", "cuda", "tensorrt", "coreml", "ureq", "openvino"] }
rusttype = { version = "0.9", default-features = false }
anyhow = { version = "1.0.75" }
regex = { version = "1.5.4" }
rand = { version = "0.8.5" }
chrono = { version = "0.4.30" }
half = { version = "2.3.1" }
dirs = { version = "5.0.1" }
ureq = { version = "2.9.1", default-features = true, features = [ "socks-proxy" ] }
walkdir = { version = "2.5.0" }
tokenizers = { version = "0.15.2" }
itertools = { version = "0.12.1" }
usearch = { version = "2.9.1" }
rayon = "1.10.0"
indicatif = "0.17.8"
