name: CI

on:
  push:
    branches: [ "main", "dev", "x" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  lints:
    name: Rustfmt & Clippy
    runs-on: ubuntu-latest
    container: jrottenberg/ffmpeg:7.1-ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get update --fix-missing
          DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential ca-certificates clang curl pkg-config protobuf-compiler

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

  check:
    name: cargo-check
    runs-on: ubuntu-latest
    container: jrottenberg/ffmpeg:7.1-ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get update --fix-missing
          DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential ca-certificates clang curl pkg-config protobuf-compiler

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check
        run: cargo check --all-features --all-targets

  test:
    name: cargo-test
    runs-on: ubuntu-latest
    container: jrottenberg/ffmpeg:7.1-ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get update --fix-missing
          DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential ca-certificates clang curl pkg-config protobuf-compiler

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Test
        run: cargo +nightly test --all-features --all-targets 

  build-linux:
    needs: test
    name: cargo build / linux / ffmpeg ${{ matrix.ffmpeg_version }}
    runs-on: ubuntu-latest
    container: jrottenberg/ffmpeg:${{ matrix.ffmpeg_version }}-ubuntu

    strategy:
      matrix:
        ffmpeg_version: [ "5.0", "5.1", "6.0", "6.1", "7.0", "7.1" ]  # "4.3", "4.4"
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get update --fix-missing
          DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential ca-certificates clang curl pkg-config protobuf-compiler

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --all-features

  build-windows:
    needs: test
    name: cargo build / windows
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Cache Cargo dependencies
      - name: Cache Cargo dependencies
        id: cache-cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      # Cache Scoop installations
      - name: Cache Scoop installations
        id: cache-scoop
        uses: actions/cache@v4
        with:
          path: |
            ~/scoop
            ~\scoop
          key: ${{ runner.os }}-scoop-packages-${{ hashFiles('.github/workflows/rust-ci.yml') }}
        
      - name: Setup Scoop
        uses: MinoruSekine/setup-scoop@v4.0.1
        with:
          install_scoop: ${{ steps.cache-scoop.outputs.cache-hit != 'true' }}
          buckets: extras
          apps: ffmpeg protobuf
          update_path: true
          
      - name: Build
        run: cargo build --all-features
        env:
          FFMPEG_DIR: ${{ github.workspace }}\scoop\apps\ffmpeg\current
